swagger: "2.0"
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: "1.0.1"
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /accounts/:
    get:
      tags:
        - User Module
      summary: Retrieve User Account Information
      description: Retrieve information about user accounts.
      responses:
        "200":
          description: Successfully retrieved user accounts
          schema:
            $ref: "#/definitions/User"
        "400":
          description: Bad Request - Invalid Fields
        "401":
          description: Unauthorized - Authentication Required
        "404":
          description: Not Found - No user accounts found
        "500":
          description: Internal Server Error
  /accounts/{accountId}/transactions/:
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Retrieve Account Transactions
      description: Retrieve transactions associated with a user account.
      parameters:
        - in: path
          name: accountId
          description: The ID of the user account
          type: string
          required: true
      responses:
        "200":
          description: Successfully retrieved account transactions
          schema:
            type: array
            items:
              $ref: "#/definitions/TransactionDetails"
        "400":
          description: Bad Request - Invalid Fields
        "401":
          description: Unauthorized - Authentication Required
        "404":
          description: Not Found - User account or transactions not found
        "500":
          description: Internal Server Error
  /accounts/{accountId}/transactions/{transactionId}:
    parameters:
      - in: path
        name: accountId
        description: The ID of the user account
        type: string
        required: true
      - in: path
        name: transactionId
        description: The ID of the transaction
        type: integer
        required: true
    get:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Retrieve Transaction Details
      description: Retrieve details of a specific transaction.
      responses:
        "200":
          description: Successfully retrieved transaction details
          schema:
            $ref: "#/definitions/TransactionDetails"
        "400":
          description: Bad Request - Invalid Fields
        "401":
          description: Unauthorized - Authentication Required
        "404":
          description: Not Found - User account or transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update Transaction Category
      description: Update category of a specific transaction.
      parameters:
        - in: path
          name: accountId
          description: The ID of the user account
          type: string
          required: true
        - in: path
          name: transactionId
          description: The ID of the transaction
          type: integer
          required: true
        - in: body
          name: transaction
          description: The updated transaction category
          required: true
          schema:
            $ref: "#/definitions/UpdatedTransactionCategory"
      responses:
        "200":
          description: Transaction category updated successfully
        "400":
          description: Bad Request - Invalid Fields
        "401":
          description: Unauthorized - Authentication Required
        "404":
          description: Not Found - User account or transaction not found
        "500":
          description: Internal Server Error
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete Transaction Category
      description: Delete category of a specific transaction.
      parameters:
        - in: path
          name: accountId
          description: The ID of the user account
          type: string
          required: true
        - in: path
          name: transactionId
          description: The ID of the transaction
          type: integer
          required: true
      responses:
        "204":
          description: Transaction category deleted successfully
        "401":
          description: Unauthorized - Authentication Required
        "404":
          description: Not Found - User account or transaction not found
        "500":
          description: Internal Server Error
  /accounts/{accountId}/transactions/{transactionId}/note:
    delete:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Delete Transaction Note
      description: Delete note of a specific transaction.
      parameters:
        - in: path
          name: accountId
          description: The ID of the user account
          type: string
          required: true
        - in: path
          name: transactionId
          description: The ID of the transaction
          type: integer
          required: true
      responses:
        "204":
          description: Transaction note deleted successfully
        "401":
          description: Unauthorized - Authentication Required
        "404":
          description: Not Found - User account or transaction not found
        "500":
          description: Internal Server Error
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Add Transaction Note
      description: Add a note to a specific transaction.
      parameters:
        - in: path
          name: accountId
          description: The ID of the user account
          type: string
          required: true
        - in: path
          name: transactionId
          description: The ID of the transaction
          type: integer
          required: true
        - in: body
          name: transaction
          description: The updated transaction note
          required: true
          schema:
            $ref: "#/definitions/UpdatedTransactionNote"
      responses:
        "201":
          description: Note added successfully
        "400":
          description: Bad Request - Invalid Fields
        "401":
          description: Unauthorized - Authentication Required
        "404":
          description: Not Found - User account or transaction not found
        "500":
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: Update Transaction Note
      description: Update note of a specific transaction.
      parameters:
        - in: path
          name: accountId
          description: The ID of the user account
          type: string
          required: true
        - in: path
          name: transactionId
          description: The ID of the transaction
          type: integer
          required: true
        - in: body
          name: transaction
          description: The updated transaction note
          required: true
          schema:
            $ref: "#/definitions/UpdatedTransactionNote"
      responses:
        "200":
          description: Transaction note updated successfully
        "400":
          description: Bad Request - Invalid Fields
        "401":
          description: Unauthorized - Authentication Required
        "404":
          description: Not Found - User account or transaction not found
        "500":
          description: Internal Server Error
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: The email address of the user
      password:
        type: string
        description: The password of the user
      firstName:
        type: string
        description: The first name of the user
      lastName:
        type: string
        description: The last name of the user
      userName:
        type: string
        description: The public username of the user
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  UpdatedTransactionCategory:
    type: object
    properties:
      category:
        type: string
        description: The category of the transaction
        enum:
          - OtherCategory1
          - OtherCategory2
          # Add more categories as needed
  UpdatedTransactionNote:
    type: object
    properties:
      note:
        type: string
        description: Additional notes for the transaction
  AccountTransactions:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          date:
            type: string
          description:
            type: string
          amount:
            type: string
          type:
            type: string
          category:
            type: string
          note:
            type: string
  TransactionDetails:
    type: object
    properties:
      date:
        type: string
        description: The date of the transaction
